site_name: Gradual - Stress Testing Framework
site_description: A comprehensive Python stress testing framework for applications and systems
site_author: Gradual Load Testing Team
site_url: https://gradual-load-testing.github.io/gradual

repo_name: Gradual-Load-Testing/gradual
repo_url: https://github.com/Gradual-Load-Testing/gradual
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            show_category_heading: true
            heading_level: 2
            members_order: source
            docstring_style: google
            preload_modules: [gradual]
            filters: ["!^_"]
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
            # The above 'format' line causes a YAML error if the Python object is not available.
            # To avoid the error, you can remove the 'format' line if you don't need custom formatting,
            # or ensure the Python object is importable in your environment.
            # If you want to avoid the error and still use mermaid, you can just use:
            # - name: mermaid
            #   class: mermaid


  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Getting Started: getting_started.md
  - User Guide:
      - User Guide: user_guide.md
      - Configuration: configuration_reference.md
  - Development Guide: dev_guide.md
  - API Reference:
      - Overview: api/overview.md
      - Core Modules:
          - Base Classes: api/base.md
          - Configuration: api/configs.md
          - Constants: api/constants.md
          - Exceptions: api/exceptions.md
          - Reporting: api/reporting.md
          - Runners: api/runners.md
      - Configuration:
          - Parser: api/parser.md
          - Phase: api/phase.md
          - Request: api/request.md
          - Scenario: api/scenario.md
          - Validation: api/validate.md
      - Base:
          - Orchestrator: api/orchestrator.md
      - Constants:
          - Request Types: api/request_types.md
      - Reporting:
          - Adapters: api/adapters.md
          - Logger: api/logger.md
          - Statistics: api/stats.md
          - Base Adapters: api/base.md
          - Logging Adapters: api/logging.md
      - Runners:
          - Iterators: api/iterators.md
          - Phase Runner: api/phase.md
          - Request Runner: api/request.md
          - Main Runner: api/runner.md
          - Scenario Runner: api/scenario.md
          - Session: api/session.md
          - HTTP Request: api/Http.md
          - SocketIO Request: api/SocketIO.md
          - Base Request: api/base.md
  - Examples: examples.md
  - Contributing: contributing.md

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/Gradual-Load-Testing/gradual
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/gradual_testing
#   analytics:
#     provider: google
#     property: !ENV GOOGLE_ANALYTICS_KEY
#   version:
#     provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
