version: '3.8'

services:
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app               # Live reload code edits (dev mode)
      - ./server_logs:/app/logs      # Persist and access logs
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload   
